use_frameworks!

 def shared_pods
  pod 'SwiftlySalesforce'
  pod 'SwiftyJSON', '~> 2.0'
  pod 'FCAlertView', :git => 'https://github.com/nimati/FCAlertView'
end

 target 'qtilities_Example' do
   platform :ios, '9.3'

   source 'https://github.com/CocoaPods/Specs.git'
   pod 'qtilities', :path => '../'
  
   #source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' 
 
   shared_pods
 end


